services:
  postgres:
    image: 'postgres:latest'
    container_name: playtogether
    environment:
      - 'POSTGRES_DB=playtogether_db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_HOST_AUTH_METHOD: md5'
    ports:
      - "5432:5432"
