version: '3.8'

secrets:
  server-certificate:
    file: ./secret.env

services:
  app:
    build: .
    container_name: playtogether_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/playtogether_db
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"

  postgres:
    image: 'postgres:latest'
    container_name: playtogether_db
    environment:
      - POSTGRES_DB=playtogether_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - "5432:5432"
