spring:
  datasource:
    url: test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
    path: /graphql


security:
  jwt:
    jwtExpirationDate: 3600000

logging:
  level:
    .org.springframework.security: trace



