name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build the Docker image with tags
      - name: Build Docker image
        run: |
          IMAGE_NAME=wojtur/playtogether_app
          IMAGE_TAG=${{ github.run_number }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_EMAIL }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          IMAGE_NAME=wojtur/playtogether_app
          docker push $IMAGE_NAME:${{ github.run_number }}
          docker push $IMAGE_NAME:latest

      # Deploy to Server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest image from Docker Hub
            docker pull wojtur/playtogether_app:latest

            # Stop and remove the existing Docker container
            docker stop playtogether_app || true
            docker rm playtogether_app || true

            # Check if any process is using port 8080 and kill it
            if lsof -i :8080 -t > /tmp/pid; then
              echo "Killing process running on port 8080..."
              kill -9 $(cat /tmp/pid)
            fi

            # Run the new container
            docker run -d --name playtogether_app \
              --network=playtogether_net \
              -p 8080:8080 \
              -v /home/playtogether/application.yml:src/main/resources/application.yml \
              wojtur/playtogether_app:latest
